Basilisk.Web/Controllers/SalesmanController.cs
using Basilisk.DataAccess.Models;
using Microsoft.AspNetCore.Mvc;
using Basilisk.ViewModel.Salesman;
using Microsoft.AspNetCore.Mvc.Rendering;
using Basilisk.ViewModel.Product;
using System.Net;
using Basilisk.ViewModel.Region;
using Basilisk.Provider;

namespace Basilisk.Web.Controllers
{

    public class SalesmanController : BaseController
    {
       
        [HttpGet]
        public IActionResult Index(int page=1, string searchID="")
        {
            SetUsernameRole(User.Claims);
            var salesman = SalesmanProvider.GetProvider().GetIndex(page, searchID);

            return View(salesman);
        }

        [HttpGet]
        public IActionResult Add()
        {
            var model = SalesmanProvider.GetProvider().GetAddForm();
            
            return View("Add", model);
        }

        [HttpGet]
        public IActionResult Edit(string id) //nama parameter harus id karena itu dari view
        {

            var model = SalesmanProvider.GetProvider().GetUpdateData(id);
            return View("Edit", model);
        }

        [HttpPost]
        public IActionResult Add(AddEditSalesmanViewModel model) 
        {
            if (ModelState.IsValid)
            {
                try
                {
                    SalesmanProvider.GetProvider().AddData(model);
                }
                catch
                {
                    return View("Add", model);
                }
                return RedirectToAction("Index");

            }

            model.DropdownSuperiorEmp = SalesmanProvider.GetProvider().GetSales();
            return View("Add", model);
        }

        [HttpPost]
        public IActionResult Edit(AddEditSalesmanViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    SalesmanProvider.GetProvider().EditData(model);
                }
                catch
                {
                    return View("Edit", model);
                }
                return RedirectToAction("Index");

            }

            model.DropdownSuperiorEmp = SalesmanProvider.GetProvider().GetSales();
            return View("Edit", model);
        }

        
        [HttpGet]
        public IActionResult Details(string id)
        {

            var model = SalesmanProvider.GetProvider().GetIndexDetail(id);

            return View("DetailSalesman", model);
        }

        [AcceptVerbs("POST", "GET")]
        public IActionResult Delete(string id)
        {
            if (SalesmanProvider.GetProvider().DeleteData(id))
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("FailDelete");
            }
            
        }
        
    }
}

Basilisk.Web/Views/Salesman/Add.cshtml
@using Basilisk.ViewModel.Salesman
@model AddEditSalesmanViewModel
@{
    ViewData["Title"] = "Salesman Add";

}

<form method="POST" asp-action="Add" class="Save">

    <div class="field-row">
        <label>Employee Number</label>
        <input placeholder="EmployeeNumber" asp-for="EmployeeNumber" />
        <span asp-validation-for="EmployeeNumber"></span>
    </div>

    <div class="field-row">
        <label>FirstName</label>
        <input placeholder="FirstName" asp-for="FirstName" />
        <span asp-validation-for="FirstName"></span>
    </div>

    <div class="field-row">
        <label>LastName</label>
        <input placeholder="LastName" asp-for="LastName" />
        <span asp-validation-for="LastName"></span>
    </div>

    <div class="field-row">
        <label>Level</label>
        <input placeholder="Level" asp-for="Level" />
        <span asp-validation-for="Level"></span>
    </div>

    <div class="field-row">
        <label>BirthDate</label>
        <input type="date" placeholder="BirthDate" asp-for="@Model.BirthDate" />
        <span asp-validation-for="BirthDate"></span>
    </div>

    <div class="field-row">
        <label>HireDate</label>
        <input type="date" placeholder="HireDate" asp-for="@Model.HiredDate" />
        <span asp-validation-for="HiredDate"></span>
    </div>

    <div class="field-row">
        <label>Address</label>
        <textarea placeholder="Address" asp-for="Address"></textarea>
    </div>
    <div class="field-row">
        <label>City</label>
        <input placeholder="City" asp-for="City" />
    </div>

    <div class="field-row">
        <label>Phone</label>
        <input placeholder="Phone" asp-for="Phone" />
        <span asp-validation-for="Phone"></span>
    </div>

    <div class="field-row">
        <label>Superior</label>
        <select asp-for="SuperiorEmployeeNumber" asp-items="Model.DropdownSuperiorEmp">
            <option selected>-- Select Superior --</option>
        </select>
        <span asp-validation-for="SuperiorEmployeeNumber"></span>
    </div>

    @*
    <input asp-for="DropdownSuperiorEmployee" style="display:none;"/>*@

    <button type="submit" class="btn">Save</button>
</form>

Basilisk.Web/Views/Salesman/DetailSalesman.cshtml
@using Basilisk.ViewModel.Salesman
@model DetailsSalesmanViewModel
@{
    ViewData["Title"] = "Salesman Detail";

}

<h1> Region dari Salesman @Model.FirstName @Model.LastName</h1>

<div class="field-col">
    <h5>Id : @Model.EmployeeNumber</h5>
    <h5>Level : @Model.Level</h5>
    <h5>BirthDate : @Model.BirthDate</h5>
    <h5>Hire Date : @Model.HireDate</h5>
    <h5>Address : @Model.Address</h5>
    <h5>City : @Model.City</h5>
    <h5>Phone : @Model.Phone</h5>
    <h5>Superior : @Model.SuperiorEmployee</h5>

</div>

<table>
    <thead>
        <tr>
            <th colspan="2">ID</th>
            <th colspan="3">City</th>
            <th colspan="4">Remark</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model.GridRegion)
        {
            <tr>
                <td colspan="2">@item.Id</td>
                <td colspan="3">@item.City</td>
                <td colspan="4">@item.Remark</td>
            </tr>
            
        }
    </tbody>
</table>

Basilisk.Web/Views/Salesman/Edit.cshtml
@using Basilisk.ViewModel.Salesman
@model AddEditSalesmanViewModel
@{
    ViewData["Title"] = "Salesman Edit";

}

<form method="POST" asp-action="Edit" class="Save">

    <div class="field-row">
        <label>Employee Number</label>
        <input placeholder="EmployeeNumber" asp-for="EmployeeNumber" readonly/>
        <span asp-validation-for="EmployeeNumber"></span>
    </div>

    <div class="field-row">
        <label>FirstName</label>
        <input placeholder="FirstName" asp-for="FirstName" />
        <span asp-validation-for="FirstName"></span>
    </div>

    <div class="field-row">
        <label>LastName</label>
        <input placeholder="LastName" asp-for="LastName" />
        <span asp-validation-for="LastName"></span>
    </div>

    <div class="field-row">
        <label>Level</label>
        <input placeholder="Level" asp-for="Level" />
        <span asp-validation-for="Level"></span>
    </div>

    <div class="field-row">
        <label>BirthDate</label>
        <input type="date" placeholder="BirthDate" asp-for="@Model.BirthDate" />
        <span asp-validation-for="BirthDate"></span>
    </div>

    <div class="field-row">
        <label>HireDate</label>
        <input type="date" placeholder="HireDate" asp-for="@Model.HiredDate" />
        <span asp-validation-for="HiredDate"></span>
    </div>

    <div class="field-row">
        <label>Address</label>
        <textarea placeholder="Address" asp-for="Address"></textarea>
    </div>
    <div class="field-row">
        <label>City</label>
        <input placeholder="City" asp-for="City" />
    </div>

    <div class="field-row">
        <label>Phone</label>
        <input placeholder="Phone" asp-for="Phone" />
    </div>

    <div class="field-row">
        <label>Superior</label>
        <select asp-for="SuperiorEmployeeNumber" asp-items="Model.DropdownSuperiorEmp">
            <option selected>-- Select Superior --</option>
        </select>
        <span asp-validation-for="SuperiorEmployeeNumber"></span>
    </div>

    @*
    <input asp-for="DropdownSuperiorEmployee" style="display:none;"/>*@

    <button type="submit" class="btn">Save</button>
</form>

Basilisk.Web/Views/Salesman/FailDelete.cshtml
<h1>Failed Deleted Data</h1>

Basilisk.Web/Views/Salesman/Index.cshtml
@using Basilisk.ViewModel.Salesman
@model IndexSalesmanViewModel
@{
    ViewData["Title"] = "Salesman Index";

}

<h1>Total data di table Salesman :@Model.TotalData  </h1>

<form method="GET" asp-controller="Salesman" asp-action="Index">
    <div class="field-row">
        <label for="Name">ID</label>
        <input type="text" name="searchID" id="searchID" value="@Model.SearchID" />
    </div>
    <button type="submit" class="btn">SEARCH</button>

</form>

<a class="btn" id="addBtn" asp-controller="Salesman" asp-action="Add">ADD</a>



<table>
    <thead>
        <tr>
            <th>Action</th>
            <th>ID</th>
            <th>Full Name</th>
            <th>Level</th>
            <th>BirthDate</th>
            <th>HireDate</th>
            <th>Address</th>
            <th>City</th>
            <th>Phone</th>
            <th>Superior</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Salesmen)
        {
            <tr>
                <td>
                    <a class="btn btn-update" asp-controller="Salesman" asp-action="Edit" asp-route-id="@item.EmployeeNumber"><i class="fa fa-pencil"><span>Edit</span></i></a>
                    <a class="btn btn-delete" asp-controller="Salesman" asp-action="Delete" asp-route-id="@item.EmployeeNumber"><i class="fa fa-trash"><span>Hapus</span></i></a>
                    <a class="btn btn-detail" asp-controller="Salesman" asp-action="Details" asp-route-id="@item.EmployeeNumber"><i class="fa fa-trash"><span>Detail</span></i></a>
                </td>
                <td>@item.EmployeeNumber</td>
                <td>@item.FirstName @item.LastName</td>
                <td>@item.Level</td>
                <td>@item.BirthDate</td>
                <td>@item.HireDate</td>
                <td>@item.Address</td>
                <td>@item.City</td>
                <td>@item.Phone</td>
                <td>@item.SuperiorEmployee</td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="10">
                <div>
                    @for (int i = 1; i <= Model.TotalHalaman; i++)
                    {

                        <a class="btn" asp-action="Index" asp-route-page="@i"
                        asp-route-idPage="@Model.SearchID">@i</a>

                    }
                </div>

            </td>

        </tr>
    </tfoot>
</table>