Basilisk.Web/Controllers/RegionController.cs
using Basilisk.DataAccess.Models;
using Basilisk.Provider;
using Basilisk.ViewModel.Region;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Basilisk.Web.Controllers
{

    public class RegionController : BaseController
    {
        #region Index

        [HttpGet]
        public IActionResult Index(int page=1, string searchCity="")
        {
            SetUsernameRole(User.Claims);
            var model = RegionProvider.GetProvider().GetIndex( page, searchCity);

            return View(model);

        }

        #endregion

        #region Add - Edit
        [HttpGet]
        public IActionResult Add()
        {
            var model = RegionProvider.GetProvider().GetAddForm();
            return View("Upsert", model);
        }

        [HttpGet]
        public IActionResult Edit(long idRegion)
        {
            var model = RegionProvider.GetProvider().GetEditData(idRegion);
            return View("Upsert", model);

        }

        [HttpPost]
        public IActionResult Save(UpsertRegionViewModel model)
        {
            if(ModelState.IsValid)
            {
                try
                {

                    RegionProvider.GetProvider().SaveData(model);
                }
                catch (Exception ex)
                {
                    throw;
                }
                return RedirectToAction("Index");

            }
            else
            {
                return View("Upsert",model);
            }
            
        }

        #endregion


        #region Delete

        [AcceptVerbs("POST", "GET")]
        public IActionResult Delete(long idRegion)
        {
            if (RegionProvider.GetProvider().DeleteData(idRegion))
            {
                return RedirectToAction("Index");
                
            }
            else
            {
                return View("FailDelete");
            }
          ;
        }

        #endregion
    }
}

Basilisk.Web/Views/Region/FailDelete.cshtml
<h1>Failed Deleted Data</h1>

Basilisk.Web/Views/Region/Index.cshtml
@using Basilisk.ViewModel.Region
@model IndexRegionViewModel
@{
    ViewData["Title"] = "Region Index";

}

<form method="GET" asp-controller="Region" asp-action="Index">
    <div class="field-row">
        <label for="regName">Region</label>
        <input type="text" name="searchCity" value="@Model.SearchCity" />


    </div>
    
    <button type="submit" class="btn">SEARCH</button>

</form>

<a class="btn" id="addBtn" asp-controller="Region" asp-action="Add">ADD</a>


<h1>Total data di table Region : @Model.TotalData  </h1>

<table>
    <thead>
        <tr>
            <th>Action</th>
            <th>ID</th>
            <th>City</th>
            <th>Remark</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ListRegion)
        {
            <tr>
                <td>
                    <a class="btn btn-update" asp-controller="Region" asp-action="Edit" asp-route-idRegion="@item.Id"><i class="fa fa-pencil"><span>Edit</span></i></a>
                    <a class="btn btn-delete" asp-controller="Region" asp-action="Delete" asp-route-idRegion="@item.Id"><i class="fa fa-trash"><span>Hapus</span></i></a>
                </td>
                <td>@item.Id</td>
                <td>@item.City</td>
                <td>@item.Remark</td>

            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="4">
                <div>
                    @for (int i = 1; i <= Model.TotalHalaman; i++)
                    {

                        <a class="btn" asp-action="Index" asp-route-page="@i"
                       asp-route-searchCity="@Model.SearchCity">@i</a>

                    }
                </div>

            </td>

        </tr>
    </tfoot>
</table>

Basilisk.Web/Views/Region/Upsert.cshtml
@using Basilisk.ViewModel.Region
@model UpsertRegionViewModel
@{
    ViewData["Title"] = "Region Add-Edit";

}


<form method="POST" action="Save">

    <input asp-for="Id"/>

    <div class="field-row">
        <label asp-for="City"></label>
        <input placeholder="CityName" asp-for="City" />
        <span asp-validation-for="City"></span>
    </div>
    <div class="field-row">
        <label>Remark</label>
        <input placeholder="Remark" asp-for="Remark" />
    </div>    

    <button type="submit" class="btn">Save</button>
</form>